In [6]:
import torch
num=4

adj=torch.arange(num*num)-(num*num/2)
adj=adj.reshape(num,num)
adj=adj.tanh()
adj

tensor([[-1.0000, -1.0000, -1.0000, -0.9999],
        [-0.9993, -0.9951, -0.9640, -0.7616],
        [ 0.0000,  0.7616,  0.9640,  0.9951],
        [ 0.9993,  0.9999,  1.0000,  1.0000]])

In [7]:

mask = torch.zeros(num, num)
mask.fill_(float("0"))
v, id = (adj.abs() + torch.rand_like(adj) * 0.01).topk(2, 1)
mask.scatter_(1, id, v.fill_(1))
adj = adj * mask
adj

tensor([[-0.0000, -1.0000, -0.0000, -0.9999],
        [-0.9993, -0.9951, -0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.9640,  0.9951],
        [ 0.0000,  0.9999,  0.0000,  1.0000]])

In [ ]:
from torch_geometric.nn.aggr import LSTMAggregation
import torch
from torch.nn import LSTM
w=3
b=5
v=2
lstm=LSTM(v,4)

# x=torch.arange(w*b*v).reshape((b,v,w)).float().contiguous()
x=torch.arange(v).repeat(b,w).reshape(b,w,v).float().contiguous()
# x=torch.zeros(b,v,w)
# x[0][0]=torch.arange(w)
# x[-1][0]=torch.arange(w)
x=x.contiguous()
# # x=x.view(-1,w).contiguous()
# # print(x[0])
# # # lstm(x,dim=-1)
# x=x.transpose(1,2)
# x.shape
print(x[0],x[-1],x.shape)


In [ ]:
lstm(x)[0][:,-1,:].shape

In [ ]:
y,_=lstm(x)
print(y[0],y[-1],y[0].shape)
y[:,:,-1]

In [ ]:
x[:,0,:].unsqueeze(-1)

In [ ]:
lstm(x[:,0,:])

In [ ]:
torch.tensor([lstm(x[:,i,:]) for i in range(v)])


In [ ]:
y=torch.tensor([lstm(x[i]) for i in range(b)]).reshape(b,v)
y

In [ ]:
m = torch.nn.BatchNorm1d(2, affine=False,eps=0)
input = torch.arange(8).reshape(2,2,2).float()
# print(input)
input:torch.Tensor= m(input)
input#.transpose(0,1).sum((-1))

In [ ]:
print(input.sum(-1))
print(input[0][0][0]+input[0][1][0]+input[0][2][0])

In [ ]:
import torch
from torch_geometric.data import Data
from torch_geometric.nn import GCN,GCNConv
from torch_geometric.utils import to_networkx
from torch_geometric.nn import MessagePassing

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1],
                            [0, 2],
                           [2, 0],
                           ], dtype=torch.long)
x = torch.tensor([[-2], [3], [5]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
data

In [ ]:
n=to_networkx(data=data)

In [ ]:

l1=GCNConv(-1,2,add_self_loops=False,aggr="max")

In [ ]:

l1(data.x,data.edge_index)

In [ ]:
print(l1.lin.weight)

In [ ]:
l1.lin(x)

In [ ]:
# Example tensor
tensor = torch.tensor([0.5, 1.2, 3.7, 0.9, 2.5])

# Define threshold and value R
threshold = 1.0
R = -1

# Apply the mapping
new_tensor = torch.where(tensor > threshold, torch.tensor(1), torch.tensor(R))

print(new_tensor)

In [ ]:
x=torch.arange(1,11).float()
y=x+1
l=torch.nn.MSELoss(reduce=False)
l(x,y)>1

In [ ]:
feature=4

a=[]
b=[]
for i in range(feature):
    for j in range(feature):
        if i!=j:
            a.append(i)
            b.append(j)
edges=[torch.tensor([a,b])]

In [ ]:
m = GDN(
    edge_index_sets=edges,topk=2, node_num=feature, task=Tasks.next_label
)

In [ ]:

x = torch.rand([10, feature, 3])
m(x, None)

In [ ]:
l=torch.arange(25).reshape(5,-1)
print(l)
l[:,0:3]

In [ ]:

# Number of unique items and the size of each embedding vector
num_items = 10  # Assume we have 10 unique items
embedding_dim = 4  # Each item will be represented as a 4-dimensional vector

# Define the embedding layer
w=torch.randn([num_items, embedding_dim])
w


In [ ]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.l=torch.nn.Linear(5,6)
        self.w=torch.nn.Parameter(
            torch.ones([3,6])
        )
    def forward(self,x):
        x=self.l(x)
        x=self.w.matmul(x)
        return x
        

In [ ]:
model=Model()
for p in model.parameters():
    print(p.shape)
model(torch.rand(5))

In [ ]:

embedding_layer = torch.nn.Embedding(num_items, embedding_dim,_weight=w)


In [ ]:
a=torch.rand(8)
print(a)
dp = torch.nn.Dropout(0.5)
dp(a)

In [ ]:
w[5]

In [ ]:

# Example item IDs (e.g., items bought by a user)
item_ids = torch.tensor([2, 5, 7], dtype=torch.long)

# Get the embeddings for the given item IDs
item_embeddings = embedding_layer(item_ids)

print("Item IDs:", item_ids)
print("Corresponding Embeddings:\n", item_embeddings)


In [ ]:
bn=torch.nn.BatchNorm1d(embedding_dim)
out:torch.Tensor=bn(item_embeddings)
out

In [ ]:
bn(torch.randn(3, embedding_dim))

In [13]:
import torch
batch=5
node=5
w=3
x=torch.rand(batch*node*w).reshape(batch,node , w)
ypred=x.mean(dim=-1).unsqueeze(-1)
ypred.squeeze_(-1)
print(ypred.shape)
ypred

torch.Size([5, 5])


tensor([[0.6290, 0.2732, 0.3812, 0.4583, 0.1691],
        [0.4339, 0.2382, 0.3063, 0.5761, 0.6269],
        [0.8231, 0.7078, 0.5333, 0.4277, 0.3112],
        [0.2364, 0.4929, 0.4719, 0.5529, 0.1795],
        [0.5073, 0.1578, 0.7355, 0.5590, 0.6385]])

In [14]:
meds=ypred.median(0).values
meds


tensor([0.5073, 0.2732, 0.4719, 0.5529, 0.3112])

In [15]:
q=torch.quantile(ypred,torch.tensor([.25,.75]),0)
q=q[1]-q[0]
q

tensor([0.1952, 0.2547, 0.1521, 0.1007, 0.4474])

In [ ]:
y_pred_norm=(ypred-meds).abs()/q


tensor([[0.6237, 0.0000, 0.5965, 0.9398, 0.3176],
        [0.3763, 0.1376, 1.0885, 0.2296, 0.7057],
        [1.6178, 1.7059, 0.4035, 1.2433, 0.0000],
        [1.3880, 0.8624, 0.0000, 0.0000, 0.2943],
        [0.0000, 0.4533, 1.7323, 0.0602, 0.7315]])

In [19]:
y_pred_norm.max(-1)

torch.return_types.max(
values=tensor([0.9398, 1.0885, 1.7059, 1.3880, 1.7323]),
indices=tensor([3, 2, 1, 0, 2]))

In [ ]:
threshold=y_pred_norm.max()

tensor(1.7323)

In [15]:
ytruth=torch.randint_like(ypred,0,2)
print(ytruth.shape)
ytruth

torch.Size([2, 5, 1])


tensor([[[0.],
         [1.],
         [0.],
         [1.],
         [1.]],

        [[1.],
         [0.],
         [1.],
         [1.],
         [0.]]])

In [19]:
loss_fn=torch.nn.L1Loss(reduction='none')
loss=loss_fn(ypred,ytruth)
print(loss.shape)
loss=loss.squeeze(-1)
loss

torch.Size([2, 5, 1])


tensor([[0.8124, 0.3357, 0.3137, 0.1109, 0.4693],
        [0.6169, 0.6849, 0.6988, 0.3186, 0.4871]])

In [18]:
all_loss=torch.zeros(10,node)
all_loss

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
all_loss[0:2,:]=loss
all_loss

tensor([[0.8124, 0.3357, 0.3137, 0.1109, 0.4693],
        [0.6169, 0.6849, 0.6988, 0.3186, 0.4871],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [24]:
all_loss.sum(0)

tensor([1.4293, 1.0206, 1.0125, 0.4294, 0.9564])