In [40]:
from torch_geometric.nn.aggr import LSTMAggregation
import torch
from torch.nn import LSTM
w=3
b=5
v=2
lstm=LSTM(v,4)

# x=torch.arange(w*b*v).reshape((b,v,w)).float().contiguous()
x=torch.arange(v).repeat(b,w).reshape(b,w,v).float().contiguous()
# x=torch.zeros(b,v,w)
# x[0][0]=torch.arange(w)
# x[-1][0]=torch.arange(w)
x=x.contiguous()
# # x=x.view(-1,w).contiguous()
# # print(x[0])
# # # lstm(x,dim=-1)
# x=x.transpose(1,2)
# x.shape
print(x[0],x[-1],x.shape)


tensor([[0., 1.],
        [0., 1.],
        [0., 1.]]) tensor([[0., 1.],
        [0., 1.],
        [0., 1.]]) torch.Size([5, 3, 2])


In [43]:
lstm(x)[0][:,-1,:].shape

torch.Size([5, 4])

In [28]:
y,_=lstm(x)
print(y[0],y[-1],y[0].shape)
y[:,:,-1]

tensor([[-0.0201,  0.0524, -0.0312,  0.1061],
        [ 0.0721,  0.0394, -0.0171, -0.0007],
        [ 0.1703,  0.0252,  0.0122, -0.1138]], grad_fn=<SelectBackward0>) tensor([[-0.0380,  0.1333, -0.0512,  0.1926],
        [ 0.0875,  0.1430, -0.0431,  0.0743],
        [ 0.2049,  0.1478, -0.0189, -0.0578]], grad_fn=<SelectBackward0>) torch.Size([3, 4])


tensor([[ 0.1061, -0.0007, -0.1138],
        [ 0.1549,  0.1066,  0.0466],
        [ 0.1774,  0.1563,  0.1289],
        [ 0.1878,  0.1793,  0.1674],
        [ 0.1926,  0.0743, -0.0578]], grad_fn=<SelectBackward0>)

In [3]:
x[:,0,:].unsqueeze(-1)

tensor([[[0.],
         [1.],
         [2.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [1.],
         [2.]]])

In [107]:
lstm(x[:,0,:])

tensor([[-0.0171]], grad_fn=<SelectBackward0>)

In [104]:
torch.tensor([lstm(x[:,i,:]) for i in range(v)])


tensor([-0.0171, -0.1247])

In [67]:
y=torch.tensor([lstm(x[i]) for i in range(b)]).reshape(b,v)
y

RuntimeError: shape '[10, 3]' is invalid for input of size 10

In [46]:
m = torch.nn.BatchNorm1d(2, affine=False,eps=0)
input = torch.arange(8).reshape(2,2,2).float()
# print(input)
input:torch.Tensor= m(input)
input#.transpose(0,1).sum((-1))

tensor([[[-1.2127, -0.7276],
         [-1.2127, -0.7276]],

        [[ 0.7276,  1.2127],
         [ 0.7276,  1.2127]]])

In [ ]:
print(input.sum(-1))
print(input[0][0][0]+input[0][1][0]+input[0][2][0])

In [ ]:
import torch
from torch_geometric.data import Data
from torch_geometric.nn import GCN,GCNConv
from torch_geometric.utils import to_networkx
from torch_geometric.nn import MessagePassing

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1],
                            [0, 2],
                           [2, 0],
                           ], dtype=torch.long)
x = torch.tensor([[-2], [3], [5]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
data

Data(x=[3, 1], edge_index=[2, 6])

In [ ]:
n=to_networkx(data=data)

DegreeView({0: 2, 1: 2, 2: 2})

In [86]:

l1=GCNConv(-1,2,add_self_loops=False,aggr="max")

In [96]:

l1(data.x,data.edge_index)

tensor([[-0.8724,  0.0264],
        [ 0.5816,  0.0264],
        [ 0.5816,  0.0158]], grad_fn=<AddBackward0>)

In [90]:
print(l1.lin.weight)

Parameter containing:
tensor([[-0.5816],
        [ 0.0106]], requires_grad=True)


In [85]:
l1.lin(x)

tensor([[-0.8173, -1.6407],
        [ 1.2260,  2.4610],
        [ 2.0433,  4.1017]], grad_fn=<MmBackward0>)

In [ ]:
# Example tensor
tensor = torch.tensor([0.5, 1.2, 3.7, 0.9, 2.5])

# Define threshold and value R
threshold = 1.0
R = -1

# Apply the mapping
new_tensor = torch.where(tensor > threshold, torch.tensor(1), torch.tensor(R))

print(new_tensor)

In [ ]:
x=torch.arange(1,11).float()
y=x+1
l=torch.nn.MSELoss(reduce=False)
l(x,y)>1

In [ ]:
feature=4

a=[]
b=[]
for i in range(feature):
    for j in range(feature):
        if i!=j:
            a.append(i)
            b.append(j)
edges=[torch.tensor([a,b])]

In [ ]:
m = GDN(
    edge_index_sets=edges,topk=2, node_num=feature, task=Tasks.next_label
)

In [ ]:

x = torch.rand([10, feature, 3])
m(x, None)

In [ ]:
l=torch.arange(25).reshape(5,-1)
print(l)
l[:,0:3]

In [ ]:

# Number of unique items and the size of each embedding vector
num_items = 10  # Assume we have 10 unique items
embedding_dim = 4  # Each item will be represented as a 4-dimensional vector

# Define the embedding layer
w=torch.randn([num_items, embedding_dim])
w


In [ ]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.l=torch.nn.Linear(5,6)
        self.w=torch.nn.Parameter(
            torch.ones([3,6])
        )
    def forward(self,x):
        x=self.l(x)
        x=self.w.matmul(x)
        return x
        

In [ ]:
model=Model()
for p in model.parameters():
    print(p.shape)
model(torch.rand(5))

In [ ]:

embedding_layer = torch.nn.Embedding(num_items, embedding_dim,_weight=w)


In [ ]:
a=torch.rand(8)
print(a)
dp = torch.nn.Dropout(0.5)
dp(a)

In [ ]:
w[5]

In [ ]:

# Example item IDs (e.g., items bought by a user)
item_ids = torch.tensor([2, 5, 7], dtype=torch.long)

# Get the embeddings for the given item IDs
item_embeddings = embedding_layer(item_ids)

print("Item IDs:", item_ids)
print("Corresponding Embeddings:\n", item_embeddings)


In [ ]:
bn=torch.nn.BatchNorm1d(embedding_dim)
out:torch.Tensor=bn(item_embeddings)
out

In [ ]:
bn(torch.randn(3, embedding_dim))