In [ ]:
from models import GDN



In [9]:
import torch
import torch.nn as nn


In [16]:
l=torch.arange(25).reshape(5,-1)
print(l)
l[:,0:3]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


tensor([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]])

In [ ]:

# Number of unique items and the size of each embedding vector
num_items = 10  # Assume we have 10 unique items
embedding_dim = 4  # Each item will be represented as a 4-dimensional vector

# Define the embedding layer
w=torch.randn([num_items, embedding_dim])
w


In [16]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.l=torch.nn.Linear(5,6)
        self.w=torch.nn.Parameter(
            torch.ones([3,6])
        )
    def forward(self,x):
        x=self.l(x)
        x=self.w.matmul(x)
        return x
        

In [17]:
model=Model()
for p in model.parameters():
    print(p.shape)
model(torch.rand(5))

torch.Size([3, 6])
torch.Size([6, 5])
torch.Size([6])


tensor([-0.1346, -0.1346, -0.1346], grad_fn=<MvBackward0>)

In [48]:
nn.init.kaiming_uniform_(w, a=torch.math.sqrt(5))
w

tensor([[ 0.4949,  0.2817, -0.0755,  0.4635],
        [-0.2632,  0.1586, -0.3282, -0.2517],
        [-0.0466,  0.0246,  0.1128,  0.2269],
        [ 0.4029,  0.1313, -0.0139,  0.0515],
        [-0.3996, -0.3556, -0.1169,  0.2630],
        [-0.2006,  0.3181,  0.1958, -0.2306],
        [-0.2965,  0.0233, -0.3822,  0.1961],
        [-0.1119,  0.3873, -0.1108, -0.0181],
        [-0.3743, -0.3277, -0.4429,  0.4875],
        [ 0.1949,  0.3815, -0.3666,  0.3399]])

In [ ]:

embedding_layer = nn.Embedding(num_items, embedding_dim,_weight=w)


In [51]:
a=torch.rand(8)
print(a)
dp = nn.Dropout(0.5)
dp(a)

tensor([0.3774, 0.9605, 0.5294, 0.7933, 0.0470, 0.5367, 0.1014, 0.7028])


tensor([0.7547, 1.9210, 1.0588, 1.5865, 0.0000, 1.0734, 0.0000, 1.4056])

In [12]:
w[5]

tensor([-0.0745,  0.6489,  0.0623, -0.5137])

In [11]:

# Example item IDs (e.g., items bought by a user)
item_ids = torch.tensor([2, 5, 7], dtype=torch.long)

# Get the embeddings for the given item IDs
item_embeddings = embedding_layer(item_ids)

print("Item IDs:", item_ids)
print("Corresponding Embeddings:\n", item_embeddings)


Item IDs: tensor([2, 5, 7])
Corresponding Embeddings:
 tensor([[ 0.9213, -2.3571, -0.0884,  0.1023],
        [-0.0745,  0.6489,  0.0623, -0.5137],
        [ 1.1842,  0.6372,  1.7921, -0.7124]], grad_fn=<EmbeddingBackward0>)


In [19]:
bn=nn.BatchNorm1d(embedding_dim)
out:torch.Tensor=bn(item_embeddings)
out

tensor([[ 0.4507, -1.4142, -0.7936,  1.3749],
        [-1.3862,  0.7112, -0.6170, -0.4011],
        [ 0.9355,  0.7030,  1.4105, -0.9739]],
       grad_fn=<NativeBatchNormBackward0>)

In [34]:
bn(torch.randn(3, embedding_dim))

tensor([[ 0.6865,  0.4370,  0.7290, -0.1278],
        [ 0.7275, -1.3833, -1.4140,  1.2836],
        [-1.4140,  0.9463,  0.6850, -1.1558]],
       grad_fn=<NativeBatchNormBackward0>)